version: "3.8"

services:
  graphqldb:
    image: mariadb:10.5
    container_name: Graphql_DB
    ports:
      - "3306:3306"
    environment:
      MARIADB_DATABASE: "graphql_db"
      MARIADB_USER: "root"
      MARIADB_PASSWORD: "root"
      MARIADB_ROOT_PASSWORD: "root"
      MARIADB_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - "GraphQL-DB:/var/lib/mysql"
    healthcheck:
      test: [ "CMD", "ping", "-p root" ]
volumes:
  database:
  GraphQL-DB:
    driver: local